version: 2
jobs:
   build:
     docker:
       - image: gcc:7.1
     steps:
       - checkout
       - run: echo "hello world"
       - run: gcc --version
       - run: g++ -o hello.exe sample.c
       - run: hello
